In [5]:
X1 = [2, 3, 4, 5, 6]
X2 = [3, 5, 6, 7, 8]
meanX1=sum(X1) / len(X1)
meanX2=sum(X2) / len(X2)
print(meanX1)
print(meanX2)

4.0
5.8


In [6]:
import numpy as np
deviations = [(x - meanX1) ** 2 for x in X1]
variance = sum(deviations) / 5
stdX1=np.sqrt(variance)

deviations = [(x - meanX2) ** 2 for x in X2]
variance = sum(deviations) / 5
stdX2=np.sqrt(variance)

print(stdX1)
print(stdX2)

1.4142135623730951
1.7204650534085253


In [7]:
scaledX1= [(x-meanX1) for x in X1]/stdX1
scaledX2= [(x-meanX2) for x in X2]/stdX2

print(scaledX1)
print(scaledX2)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.62746694 -0.46499055  0.11624764  0.69748583  1.27872403]


In [8]:
print(np.round(np.mean(scaledX1),2))
print(np.round(np.std(scaledX1),2))

0.0
1.0


In [9]:
print(np.round(np.mean(scaledX2),2))
print(np.round(np.std(scaledX2),2))

0.0
1.0


In [10]:
import numpy as np

meanX1 = np.mean(scaledX1)
meanX2 = np.mean(scaledX2)

covariance = sum([(scaledX1[i] - meanX1) * (scaledX2[i] - meanX2) for i in range(len(X1))]) / len(X1)

cov_matrix = np.array([[np.var(scaledX1), covariance],
                       [covariance, np.var(scaledX2)]])

print("Covariance matrix: ")
print(cov_matrix)


Covariance matrix: 
[[1.         0.98639392]
 [0.98639392 1.        ]]


In [16]:
a = 1
b = -np.trace(cov_matrix)
c = np.linalg.det(cov_matrix)
print("b:", b)
print("c:", c)
discriminant = np.sqrt(b**2 - 4*a*c)
lambda1 = (-b + discriminant) / (2*a)
lambda2 = (-b - discriminant) / (2*a)

# Print the eigenvalues
print("Eigenvalues:", lambda1, lambda2)


b: -1.9999999999999998
c: 0.027027027027026754
Eigenvalues: 1.9863939238321437 0.01360607616785614


In [12]:
# Calculate the eigenvectors from the eigenvalues
eigenvector1 = np.array([lambda1 - np.var(scaledX2), covariance])
eigenvector2 = np.array([covariance, lambda2 - np.var(scaledX1)])


eigenvector1 = eigenvector1 / np.linalg.norm(eigenvector1)
eigenvector2 = eigenvector2 / np.linalg.norm(eigenvector2)


print("Eigenvectors:")
print(eigenvector1)
print(eigenvector2)


Eigenvectors:
[0.70710678 0.70710678]
[ 0.70710678 -0.70710678]


In [13]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
# Sort the eigenvalues and eigenvectors in descending order
idx = eigenvalues.argsort()[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]
projection_matrix = eigenvectors[:, 0].reshape(-1, 1)
data_matrix = np.array([scaledX1, scaledX2]).T
projected_data = np.dot(data_matrix, projection_matrix)
print("Projected Data:\n", projected_data)


Projected Data:
 [[ 2.15079291]
 [ 0.82879797]
 [-0.08219949]
 [-0.99319696]
 [-1.90419443]]


In [14]:
from sklearn.decomposition import PCA


data_matrix = np.array([scaledX1, scaledX2]).T

pca = PCA(n_components=1)

pca_transformed_data = pca.fit_transform(data_matrix)


pca_transformed_data


array([[ 2.15079291],
       [ 0.82879797],
       [-0.08219949],
       [-0.99319696],
       [-1.90419443]])